Allow override across different placement types
open-cluster-management-io/policy-generator-plugin pull request #157
Opened 2024-04-03 16:18 UTC by zyjjay

This change will allow placements to override placementrule defaults and vice versa.

ref: https://issues.redhat.com/browse/ACM-10152

2024-04-09 20:18 UTC, dhaiducek commented
> This change will allow placements to override placementrule defaults and vice versa.

Sorry, it looks like the issue was worded poorly. I don't think we should allow overriding `Placement` for `PlacementRule`, especially when `PlacementRule` is deprecated. However, when considering the options for a particular placement Kind (file path, selector, or name), these should be override-able if provided in the `policies` array.

2024-04-10 18:03 UTC, zyjjay commented
So based on my understanding, only placement Kinds (name, fp, selector) in the policies array should override the default placement/placementRule Kinds. If a user were to specify a placementRule Kind in a policy in the policies array, but the policy default specifies a placement Kind, would the generated policy bind to a placement or a placementRule?

2024-04-10 18:22 UTC, dhaiducek commented
Sorry, you have it right--I think I got my wires crossed. Let me give this PR another look.

2024-04-10 18:26 UTC, zyjjay commented
I currently have it so that a placement Kind could override a placementRule default, and vice versa. I could modify it so that **only** placement Kinds in the policies array could override placementRule defaults if that's the desired behavior.

2024-04-10 18:31 UTC, dhaiducek commented
No, I think it's correct to have it this way. Sorry for my confusion. 😅

2024-04-10 19:33 UTC, dhaiducek requested changes
Minor testing comments, but overall looks good! Thanks for updating it (and straightening me out!).

(Optional) I think you could add one more test to test overriding PlacementRule with Placement?

2024-04-10 19:33 UTC, dhaiducek commented on internal/plugin_config_test.go
> +		t.Fatal("Did not expect errors but got one")
This should also return the error message now that it's no longer `nil`.

2024-04-10 19:33 UTC, dhaiducek commented on internal/plugin_config_test.go
> +		t.Fatal("Did not expect errors but got one")
This should also return the error message now that it's no longer `nil`.

2024-04-10 20:39 UTC, dhaiducek approved these changes
LGTM! Thanks for updating it!

2024-04-10 20:45 UTC, merged